services:
  - type: web
    name: monitoring-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python monitoring_bot.py"
    envVars:
      - key: TEAMS_WEBHOOK_URL
        value: "<TWÓJ_WEBHOOK_TUTAJ>"
      - key: CHECK_INTERVAL_SECONDS
        value: "300"
      - key: URLS_TO_CHECK
        value: "https://dolby.okta.com/,https://confluence.dolby.net/kb/,https://app.smartsheet.com/,https://dolby.ent.box.com/"
