services:
  - type: worker
    name: monitoring-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python monitoring_bot.py"
    envVars:
      - key: TEAMS_WEBHOOK_URL
        value: https://dolby.webhook.office.com/webhookb2/da4607bf-4106-4b9d-88a1-0e8087794137@05408d25-cd0d-40c8-8962-5462de64a318/IncomingWebhook/a9bc454da51f4367bebeaaf63ecfe6c1/cc9a05af-8a0a-46a2-8400-6f60cedfeded/V2JnLzypiJ1SzShBjol9R_VfWKknkTC7bk__IA8kNL17E1
      - key: CHECK_INTERVAL_SECONDS
        value: "300"
      - key: URLS_TO_CHECK
        value: "https://dolby.okta.com/,https://confluence.dolby.net/kb/,https://app.smartsheet.com/,https://dolby.ent.box.com/"
      